"""add role enum to users

Revision ID: 147c08331169
Revises: 9387d2f74622
Create Date: 2025-01-30 12:47:03.983591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

role_enum = ENUM("user", "admin", name="roleset", create_type=True)

# revision identifiers, used by Alembic.
revision: str = '147c08331169'
down_revision: Union[str, None] = '9387d2f74622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("users", sa.Column("role", role_enum, nullable=False, server_default="user"))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
